server {
    listen 80;
    server_name _;

    root /usr/share/nginx/site/html;
    index index.html;

    location / {
        try_files $uri $uri/ /index.html;
    }

    location /css/ {
        alias /usr/share/nginx/site/css/;
    }

    location /js/ {
        alias /usr/share/nginx/site/js/;
    }
}

